name: Build, Tag, and Push Cloud Run Job Images
on:
  pull_request:
    branches: [main]
    paths:
      - 'ai_content_creation/cloud_run_jobs/**'

env:
  DOCKER_REPO_NAME: europe-west2-docker.pkg.dev
  GCP_PROJECT_ID: ai-content-creation-438122
  GCP_REPOSITORY: docker-repository

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      changed_folders: ${{ steps.extract-top.outputs.top_level }}
    steps:
      - uses: actions/checkout@v4

      - id: get-folders
        uses: tj-actions/changed-files@v39
        with:
          path: ai_content_creation/cloud_run_jobs
          dir_names: true
          include_subdirs: true
          dir_names_exclude_current_dir: true
          escape_json: false
          json: true

      - id: extract-top
        shell: bash
        env:
          ALL_CHANGED: ${{ steps.get-folders.outputs.all_changed_files }}
        run: |
          tops=$(echo "$ALL_CHANGED" \
            | tr -d '[]"' \
            | tr ',' '\n' \
            | cut -d'/' -f1 \
            | sort -u \
            | jq -R -s -c 'split("\n")[:-1]')
          echo "top_level=$tops" >> $GITHUB_OUTPUT
      
      - name: debug-show-changed-folders
        run: |
          echo "Changed folders: ${{ steps.extract-top.outputs.top_level }}"
          echo "Changed folders count: $(echo ${{ steps.extract-top.outputs.top_level }} | jq length)"
        shell: bash

  build_and_push:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.changed_folders != '[]' && needs.detect_changes.outputs.changed_folders != '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJson(needs.detect_changes.outputs.changed_folders) }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set environment variables
        run: |
          GIT_COMMIT_SHA=$(git rev-parse --short HEAD)
          echo "GIT_COMMIT_SHA=$GIT_COMMIT_SHA" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_REFERENCE=${DOCKER_REPO_NAME}/${GCP_PROJECT_ID}/${GCP_REPOSITORY}/${{ matrix.folder }}:$GIT_COMMIT_SHA" >> $GITHUB_ENV

      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - run: gcloud auth configure-docker ${{ env.DOCKER_REPO_NAME }}

      - run: |
          cd ai_content_creation/cloud_run_jobs/${{ matrix.folder }}
          docker build -t ai-content-creation/${{ matrix.folder }}:${{ env.GIT_COMMIT_SHA }} .

      - run: |
          cd ai_content_creation/cloud_run_jobs/${{ matrix.folder }}
          docker tag ai-content-creation/${{ matrix.folder }}:${{ env.GIT_COMMIT_SHA }} ${{ env.DOCKER_IMAGE_REFERENCE }}

      - run: |
          cd ai_content_creation/cloud_run_jobs/${{ matrix.folder }}
          docker push ${{ env.DOCKER_IMAGE_REFERENCE }}

      - run: |
          cd infra/tf
          sed -i "s|cloud_run_job_image__${{ matrix.folder }} = .*|cloud_run_job_image__${{ matrix.folder }} = \"${{ env.DOCKER_IMAGE_REFERENCE }}\"|" terraform.tfvars

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "CICD: Update Terraform tfvars with new image: ${{ env.DOCKER_IMAGE_REFERENCE }}"
          add: "infra/tf/terraform.tfvars"
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
