name: Build, Tag, and Push Docker Images

on:
  push:
    branches:
      - main

env:
  DOCKER_REPO_NAME: europe-west2-docker.pkg.dev
  GCP_PROJECT_ID: ai-content-creation-438122
  GCP_REPOSITORY: docker-repository

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      changed_folders: ${{ steps.get-changed-folders.outputs.all_changed_files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get list of changed folders
        id: get-changed-folders
        uses: tj-actions/changed-files@v39
        with:
          path: ai_content_creation/cloud_run_jobs
          dir_names: true
          escape_json: false
          json: true
      
      - name: List all changed folders
        env:
          ALL_CHANGED_FILES: ${{ steps.get-changed-folders.outputs.all_changed_files }}
        run: |
          for folder in ${ALL_CHANGED_FILES}; do
            echo "$folder was changed"
          done

  build_and_push:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.changed_folders != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJson(needs.detect_changes.outputs.changed_folders) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variables
        run: echo "GIT_COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      
      - name: Configure Docker to use GCP Artifact Registry
        run: gcloud auth configure-docker ${{ env.DOCKER_REPO_NAME }}

      - name: Build Docker Image
        run: |
          cd ai_content_creation/cloud_run_jobs/${{ matrix.folder }}
          docker build -t ai-content-creation/${{ matrix.folder }}:${{ env.GIT_COMMIT_SHA }} .

      - name: Tag Docker Image
        run: |
          cd ai_content_creation/cloud_run_jobs/${{ matrix.folder }}
          docker tag \
          ai-content-creation/${{ matrix.folder }}:${{ env.GIT_COMMIT_SHA }} \
          ${{ env.DOCKER_REPO_NAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REPOSITORY }}/${{ matrix.folder }}:${{ env.GIT_COMMIT_SHA }}

      - name: Push Docker Image
        run: |
          cd ai_content_creation/cloud_run_jobs/${{ matrix.folder }}
          docker push ${{ env.DOCKER_REPO_NAME }}/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REPOSITORY }}/${{ matrix.folder }}:${{ env.GIT_COMMIT_SHA }}
